### ISSUE TITLE
Bierstube

### ISSUE THREAD

**Issue by marcel-liebgott** [MarauderXtreme/bookshop-schiller#40]
<no description>

@MarauderXtreme Edit:
As I announced on my [website](http://kepler.international/projects/softwaretechnologie-praktikum) I wanted to create an issue to see if we can get to an appointment for the open round in the Bierstube. Maybe the Campus as a substitute. 

But some troll was faster than me. Yeah I mean you @marcel-liebgott .

**Comment by MarauderXtreme** [comment]
Maybe we can find a date where we all are able to attend. @MDuehr @Bartmen @s3354713 @KoehlerTill

**Comment by marcel-liebgott** [comment]
thanks for your words @MarauderXtreme ;)

**Comment by chryb** [comment]
Ich lass mal ein Komment auf Deutsch hier, damit es schneller geht. Ich hoffe Ihr seit mir nicht zu sehr böse, aber ich denke aus der Bierstube (Campus) wird nichts mehr. Erstens bezweifle ich, dass ich mit der anderen Gruppe noch einen Termin finde, da sich auch bei der letzten Terminfindung nicht sehr viele fanden. Das größere Problem ist, dass ich noch eine ziemlich lernaufwendige Prüfung vor mir habe und ich danach auch kaum noch Zeit habe. Tut mir wirklich leid.

**Comment by MarauderXtreme** [comment]
Okay. Das ist zwar sehr schade, lässt sich aber nicht retten.
Danke für die Antwort.
